FROM node:23-slim

WORKDIR /app

# COPY package*.json ./
COPY shared/package*.json ./shared/
COPY shared/tsconfig.json ./shared/
COPY server/package*.json ./server/
COPY shared/src ./shared/src

WORKDIR /app/shared

RUN npm install
RUN npm run build

WORKDIR /app/server

RUN npm install

EXPOSE 5001

CMD ["npm", "run", "dev"]

