# Stage 1: build
FROM node:23-slim AS builder

WORKDIR /app


COPY package*.json ./
COPY server/package*.json ./server/
COPY shared/package*.json ./shared/

RUN npm install

COPY . .

# Build the shared package first
RUN npm run build --workspace=shared

# Build the server application
RUN npm run build --workspace=server

# Stage 2: production
FROM node:23-slim

WORKDIR /app

COPY server/package*.json ./server/
COPY shared/package*.json ./shared/

COPY --from=builder /app/server/dist ./server/dist
COPY --from=builder /app/shared/dist ./shared/dist

WORKDIR /app/shared

RUN npm install --production

WORKDIR /app/server

RUN npm install --production

EXPOSE 5001

CMD ["node", "dist/app.js"]